Raise nicer error when no route block defined
Previously, trying to use a Roda object that doesn't have a route block
would result in:

    NoMethodError:
       undefined method `call' for nil:NilClass

Now the error message is:

    RodaError:
        No route block defined for MyApp